const fs = require("fs");
const p = require("path");
const r = "E:/Pankaj-Vikram-Associates/MyTaxAssist/Registration_page/MyTaxAssist";

const lines = [];
lines.push("import React, { useState } from \"react\";");
lines.push("import { View, Text, TextInput, TouchableOpacity, TextInputProps } from \"react-native\";");
lines.push("");
lines.push("interface InputProps extends Omit<TextInputProps, \"className\"> {");
lines.push("  label?: string;");
lines.push("  error?: string;");
lines.push("  rightIcon?: React.ReactNode;");
lines.push("  onRightIconPress?: () => void;");
lines.push("  required?: boolean;");
lines.push("}");
lines.push("");
lines.push("export default function Input({ label, error, rightIcon, onRightIconPress, required, ...props }: InputProps) {");
lines.push("  const [isFocused, setIsFocused] = useState(false);");
lines.push("  const borderColor = error ? \"border-danger\" : isFocused ? \"border-info\" : \"border-border\";");
lines.push("  return (");
lines.push("    <View className=\"mb-4\">");
lines.push("      {label ? (");
lines.push("        <Text className=\"text-sm font-semibold text-textsecondary mb-1.5\">");
lines.push("          {label}");
lines.push("          {required ? <Text className=\"text-danger\">*</Text> : null}");
lines.push("        </Text>");
lines.push("      ) : null}");
lines.push('      <View className={"flex-row items-center rounded-lg border bg-surface px-3 py-2.5 " + borderColor}>');
lines.push('        <TextInput className="flex-1 text-base text-textprimary" placeholderTextColor="#8a7860" onFocus={() => setIsFocused(true)} onBlur={() => setIsFocused(false)} {...props} />');
lines.push("        {rightIcon ? (");
lines.push('          <TouchableOpacity onPress={onRightIconPress} className="ml-2 p-1" accessibilityRole="button" accessibilityLabel={props.secureTextEntry ? "Show password" : "Hide password"}>');
lines.push("            {rightIcon}");
lines.push("          </TouchableOpacity>");
lines.push("        ) : null}");
lines.push("      </View>");
lines.push('      {error ? <Text className="mt-1 text-xs text-danger">{error}</Text> : null}');
lines.push("    </View>");
lines.push("  );");
lines.push("}");

fs.writeFileSync(p.join(r, "frontend", "src", "components", "common", "Input.tsx"), lines.join("\n"), "utf8");
console.log("done");
